### ISSUE TITLE
a question please

### ISSUE THREAD

**Issue by hcgiub001** [nattadasu/animeApi#3]
Hey sorry if this isn't the right place
I'm using a kodi addon that uses TMDB database.
I seen your table and it has a purple tick with simkl (for TMDB)
what I like to know is, if I query simkl api for anime trending list.
does what you created here mean I get the result back with TMDB id's (from simkl)
so I only have to make one api call to tmdb?
would be awesome if it's true. sorry again if it's wrong place.
any help would be appreciated :)

**Comment by hcgiub001** [comment]
I found out Simkl can include the TMDB id's which is what I was after, so everything is good. :)

**Comment by nattadasu** [comment]
> does what you created here mean I get the result back with TMDB id's (from simkl)

Actually, no. The table was created as reference of what IDs you would get if you use one of providers—thus categorized as per column.

Technically, all you can do is call SIMKL API to get an info of a show, then the API will returns all IDs I've listed in the table :D

Just keep in note that SIMKL does not allow you to use other similar API to be used alongside as reference unless you want to utilize tracking feature as well.

**Comment by nattadasu** [comment]
Additionally, if you're looking for mapping across anime dedicated databases (MAL, AL, AniDB, etc) to conventional show databases (TMDB, IMDb, TVDB), then SIMKL is better choice. AniAPI only offers limited direct index to those database as I unable to found better sources.

However, if the show have Trakt ID on AniAPI index, then you can do scuffed call like MAL (via AniAPI) -> Trakt -> TMDB, IMDb, or TVDB.

**Comment by hcgiub001** [comment]
hey thanks for getting back to me. so yeah I later understood what your table was showing.
this is all to do with an addon on kodi (Fenlight) . The Dev (Tikipeter) is using TMDB database for all metadata. TMDB doesn't have a dedicated anime section and the Dev likes to not abuse API's , so using something like MAL is not an option since if I wanted to have the MAL list for most popular this week, it would have to do a call to find the ID of every anime, and it gets worse for episodes and more complication.
I realised SIMKL is literally perfect. it will return TMDB ids. so now we can query once then only use one API call to get all the lists of anime.
really happy and checked out SIMKL anime section and it's pretty good at anime data, nothing like MAL ofcourse.
now just need something similar for kdrama and I'm a happy chappy lol
nice app btw :)

**Comment by nattadasu** [comment]
> SIMKL anime section and it's pretty good at anime data

Well, it uses AniDB as source database, so obviously all metadata in AniDB were heavily moderated 😂

But because it also uses AniDB, some MAL entries, especially Specials and OVA entries will be merged into parent entry on AniDB if it was "bundled" for purchase. So, not all MAL entries is backward compatible with AniDB, although in the past MAL used AniDB as database source as well.

Anyhow, there's also MAL-like for CJK drama, MyDramaList, but unfortunately I don't see any projects or database site that offers mapping from/to MDL.... Although it was considered as *de facto* for CJK drama bruh.

**Comment by hcgiub001** [comment]
Yeah you might think it's weird to not just use MyDramalist for kdrama but everything is tied to TMDB. And the dev doesn't even really use his own addon so I can't expect him to do something so big to get Kdrama added, though we don't have a good kdrama addon for kodi (with good quality). You can still search for any kdrama inside the app. just we don't have a section for kdrama to show new users kdrama.
That's great that it get's it's data from AniDb, I think TMDB also get their data from AniDB
hope you enjoy your weekend
